src/main/webapp/WEB-INF/views/admin/add_product.jsp

test:git test

---

src/main/java/com/project/simple/admin/controller/AdminControllerImpl.java
src/main/java/com/project/simple/admin/dao/AdminDAO.java
src/main/java/com/project/simple/admin/dao/AdminDAOImpl.java
src/main/java/com/project/simple/admin/service/AdminService.java
src/main/java/com/project/simple/admin/service/AdminServiceImpl.java
src/main/resources/mybatis/mappers/admin.xml
src/main/resources/mybatis/mappers/order.xml
src/main/resources/tiles/tiles_admin.xml
src/main/webapp/WEB-INF/views/admin/admin_listorder.jsp

update : update to AdminController

---

src/main/java/com/project/simple/product/controller/ProductControllerImpl.java
src/main/java/com/project/simple/product/dao/ProductDAO.java
src/main/java/com/project/simple/product/dao/ProductDAOImpl.java
src/main/java/com/project/simple/product/service/ProductService.java
src/main/java/com/project/simple/product/service/ProductServiceImpl.java
src/main/resources/mybatis/mappers/product.xml
src/main/webapp/WEB-INF/views/admin/add_product.jsp

update: update to add product(option function)

---

src/main/java/com/project/simple/admin/controller/AdminControllerImpl.java
src/main/java/com/project/simple/admin/dao/AdminDAO.java
src/main/java/com/project/simple/admin/dao/AdminDAOImpl.java
src/main/java/com/project/simple/admin/service/AdminService.java
src/main/java/com/project/simple/admin/service/AdminServiceImpl.java
src/main/java/com/project/simple/order/controller/OrderController.java
src/main/java/com/project/simple/order/controller/OrderControllerImpl.java
src/main/java/com/project/simple/order/dao/OrderDAO.java
src/main/java/com/project/simple/order/dao/OrderDAOImpl.java
src/main/java/com/project/simple/order/service/OrderService.java
src/main/java/com/project/simple/order/service/OrderServiceImpl.java
src/main/java/com/project/simple/order/vo/OrderVO.java
src/main/resources/mybatis/mappers/admin.xml
src/main/resources/mybatis/mappers/order.xml
src/main/resources/mybatis/mappers/product.xml
src/main/resources/tiles/tiles_admin.xml
src/main/webapp/WEB-INF/views/admin/admin_listnoorder.jsp
src/main/webapp/WEB-INF/views/order/nonorder_01.jsp
src/main/webapp/WEB-INF/views/order/order_03.jsp

update : update to OrderController

---

src/main/java/com/project/simple/admin/controller/AdminControllerImpl.java
src/main/java/com/project/simple/admin/dao/AdminDAO.java
src/main/java/com/project/simple/admin/dao/AdminDAOImpl.java
src/main/java/com/project/simple/admin/service/AdminService.java
src/main/java/com/project/simple/admin/service/AdminServiceImpl.java
src/main/java/com/project/simple/order/controller/OrderControllerImpl.java
src/main/java/com/project/simple/order/dao/OrderDAO.java
src/main/java/com/project/simple/order/dao/OrderDAOImpl.java
src/main/java/com/project/simple/order/service/OrderService.java
src/main/java/com/project/simple/order/service/OrderServiceImpl.java
src/main/resources/mybatis/mappers/admin.xml
src/main/resources/mybatis/mappers/order.xml
src/main/resources/tiles/tiles_admin.xml
src/main/webapp/WEB-INF/views/admin/admin_detailNonorder.jsp
src/main/webapp/WEB-INF/views/admin/admin_listmember.jsp
src/main/webapp/WEB-INF/views/admin/admin_listnoorder.jsp
src/main/webapp/WEB-INF/views/admin/admin_listorder.jsp
src/main/webapp/WEB-INF/views/admin/admin_modNonmemorder.jsp

feat: add admin nonmemberorder function

---

src/main/java/com/project/simple/product/controller/ProductControllerImpl.java
src/main/java/com/project/simple/product/dao/ProductDAO.java
src/main/java/com/project/simple/product/dao/ProductDAOImpl.java
src/main/java/com/project/simple/product/service/ProductService.java
src/main/java/com/project/simple/product/service/ProductServiceImpl.java
src/main/java/com/project/simple/product/vo/OptionVO.java
src/main/resources/mybatis/mappers/product.xml
src/main/resources/mybatis/model/modelConfig.xml
src/main/webapp/WEB-INF/views/admin/add_product.jsp

feat: update option registration

---

src/main/java/com/project/simple/order/controller/OrderControllerImpl.java
src/main/java/com/project/simple/order/dao/OrderDAO.java
src/main/java/com/project/simple/order/dao/OrderDAOImpl.java
src/main/java/com/project/simple/order/service/OrderService.java
src/main/java/com/project/simple/order/service/OrderServiceImpl.java
src/main/java/com/project/simple/order/vo/OrderVO.java
src/main/resources/mybatis/mappers/order.xml
src/main/webapp/WEB-INF/views/admin/admin_detailNonorder.jsp
src/main/webapp/WEB-INF/views/admin/admin_detailorder.jsp
src/main/webapp/WEB-INF/views/admin/admin_listnoorder.jsp
src/main/webapp/WEB-INF/views/admin/admin_listorder.jsp
src/main/webapp/WEB-INF/views/admin/admin_modNonmemorder.jsp
src/main/webapp/WEB-INF/views/admin/admin_modmemorder.jsp

feat: add admin deliverystatus modify function

---

src/main/java/com/project/simple/product/controller/ProductControllerImpl.java
src/main/java/com/project/simple/product/dao/ProductDAO.java
src/main/java/com/project/simple/product/dao/ProductDAOImpl.java
src/main/java/com/project/simple/product/service/ProductService.java
src/main/java/com/project/simple/product/service/ProductServiceImpl.java
src/main/java/com/project/simple/product/vo/OptionVO.java
src/main/resources/mybatis/mappers/product.xml
src/main/webapp/WEB-INF/views/admin/add_product.jsp

feat: delete option selection

---

src/main/java/com/project/simple/order/dao/OrderDAOImpl.java
src/main/resources/mybatis/mappers/order.xml

update: update to deliveryStatus

---

src/main/webapp/WEB-INF/views/mypage/mypage_08.jsp
src/main/webapp/WEB-INF/views/mypage/mypage_09.jsp

docs: jsp UI update

---

src/main/java/com/project/simple/product/controller/ProductControllerImpl.java
src/main/java/com/project/simple/product/dao/ProductDAO.java
src/main/java/com/project/simple/product/dao/ProductDAOImpl.java
src/main/java/com/project/simple/product/service/ProductService.java
src/main/java/com/project/simple/product/service/ProductServiceImpl.java
src/main/resources/mybatis/mappers/product.xml
src/main/webapp/WEB-INF/views/admin/add_product.jsp
src/main/webapp/WEB-INF/views/admin/admin_detailproduct.jsp
src/main/webapp/WEB-INF/views/admin/admin_modNonmemorder.jsp
src/main/webapp/WEB-INF/views/admin/modProduct.jsp

update: update to productNum AI

---

src/main/resources/mybatis/mappers/product.xml
src/main/webapp/WEB-INF/views/product/product_detail.jsp

update : update productreview Image

---

src/main/java/com/project/simple/mypage/controller/MypageControllerImpl.java
src/main/resources/mybatis/mappers/mypage.xml
src/main/webapp/WEB-INF/views/board/Question.jsp
src/main/webapp/WEB-INF/views/common/mypage_topmenu.jsp
src/main/webapp/WEB-INF/views/mypage/mypage_01.jsp
src/main/webapp/WEB-INF/views/mypage/mypage_03.jsp
src/main/webapp/WEB-INF/views/mypage/order_detail.jsp
src/main/webapp/WEB-INF/views/mypage/order_search.jsp
src/main/webapp/WEB-INF/views/mypage/return.jsp
src/main/webapp/WEB-INF/views/mypage/return_write.jsp
src/main/webapp/WEB-INF/views/mypage/review.jsp
src/main/webapp/WEB-INF/views/mypage/review_write.jsp

docs: mypage jsp update

---

src/main/resources/mybatis/mappers/nonmember.xml
src/main/webapp/WEB-INF/views/board/AsCenter_write.jsp
src/main/webapp/WEB-INF/views/mypage/mypage_10.jsp
src/main/webapp/WEB-INF/views/mypage/review.jsp

docs : jsp UI update

---

src/main/resources/mybatis/mappers/admin.xml
src/main/resources/mybatis/mappers/board.xml
src/main/resources/mybatis/mappers/mypage.xml
src/main/webapp/WEB-INF/views/board/AsCenter.jsp
src/main/webapp/WEB-INF/views/board/Inquiry.jsp
src/main/webapp/WEB-INF/views/mypage/order_detail.jsp
src/main/webapp/WEB-INF/views/mypage/review_write.jsp

docs: board jsp update

---

src/main/java/com/project/simple/admin/controller/AdminControllerImpl.java
src/main/java/com/project/simple/mypage/controller/MypageControllerImpl.java
src/main/java/com/project/simple/mypage/service/MypageServiceImpl.java
src/main/resources/mybatis/mappers/admin.xml
src/main/webapp/WEB-INF/views/admin/productQuestion.jsp
src/main/webapp/WEB-INF/views/mypage/review.jsp

admin.xml questionSearchCount 수정

update: admin.xml update

---

src/main/webapp/WEB-INF/views/cart/cart.jsp
src/main/webapp/WEB-INF/views/product/product_detail.jsp

docs: product jsp update

---

src/main/webapp/WEB-INF/views/cart/cart.jsp
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/member/join_01.jsp
src/main/webapp/WEB-INF/views/member/join_02.jsp
src/main/webapp/WEB-INF/views/member/join_03.jsp
src/main/webapp/WEB-INF/views/mypage/deletemember.jsp
src/main/webapp/WEB-INF/views/mypage/drop_out.jsp
src/main/webapp/WEB-INF/views/storeinfomation.jsp

update: jsp update

---

src/main/java/com/project/simple/member/controller/MemberControllerImpl.java
src/main/resources/mybatis/mappers/member.xml
src/main/resources/tiles/tiles_member.xml
src/main/webapp/WEB-INF/views/member/join_04.jsp

update: memberlogin update

---

src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/product/product_bed.jsp
src/main/webapp/WEB-INF/views/product/product_detail.jsp
src/main/webapp/WEB-INF/views/product/product_sofa.jsp
src/main/webapp/WEB-INF/views/product/product_table01.jsp
src/main/webapp/WEB-INF/views/product/product_table02.jsp
src/main/webapp/WEB-INF/views/product/product_wardrobe.jsp

update: product.jsp update

---

src/main/java/com/project/simple/member/controller/MemberControllerImpl.java
src/main/java/com/project/simple/nonmember/vo/NonmemberVO.java
src/main/java/com/project/simple/product/controller/ProductControllerImpl.java
src/main/java/com/project/simple/product/dao/ProductDAO.java
src/main/java/com/project/simple/product/dao/ProductDAOImpl.java
src/main/java/com/project/simple/product/service/ProductService.java
src/main/java/com/project/simple/product/service/ProductServiceImpl.java
src/main/resources/mybatis/mappers/nonmember.xml
src/main/resources/mybatis/mappers/product.xml
src/main/resources/tiles/tiles_admin.xml
src/main/webapp/WEB-INF/views/cart/cart.jsp
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/member/join_01.jsp
src/main/webapp/WEB-INF/views/member/join_03.jsp
src/main/webapp/WEB-INF/views/member/join_04.jsp
src/main/webapp/WEB-INF/views/mypage/mypage_03.jsp
src/main/webapp/WEB-INF/views/order/nonorderinquiry.jsp
src/main/webapp/WEB-INF/views/product/product_detail.jsp

update: member Payment, nonMember Payment update
